### ISSUE TITLE
Stop button from EVCC side is not working systematically.

### ISSUE THREAD

**Issue by OSkrdgz** [EDF-Lab/eVDriveFlow#18]
Stop from the EVCC side without GUI works fine. 
Hint: The problem seems to be related to accelerated message exchange, the GUI seems to need more time to process the stop request.

**Comment by OSkrk** [comment]
Error snippet:

sh
[2022-08-07 23:23:37,999] INFO (message_handling): Message is valid.
application protocol failed to receive SSL data
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f6152898640>
transport: <_SelectorSocketTransport fd=45 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/miniconda3/envs/edf15118-20/lib/python3.8/asyncio/sslproto.py", line 546, in data_received
    self._app_protocol.data_received(chunk)
  File "/eVDriveFlow/evcc/tcp_client.py", line 83, in data_received
    self.process_incoming_message(packet)
  File "/eVDriveFlow/evcc/tcp_client.py", line 106, in process_incoming_message
    payload = v2gtp_message.payload.getfieldval("payloadContent")
  File "/miniconda3/envs/edf15118-20/lib/python3.8/site-packages/scapy/packet.py", line 411, in getfieldval
    return self.payload.getfieldval(attr)
  File "/miniconda3/envs/edf15118-20/lib/python3.8/site-packages/scapy/packet.py", line 1824, in getfieldval
    raise AttributeError(attr)
AttributeError: payloadContent
[2022-08-07 23:23:38,000] ERROR (tcp_client): payloadContent. (tcp_client.py:94)
[2022-08-07 23:23:38,482] WARNING (timer): Message timer requirement not fulfilled: over 0.50 seconds). (timer.py:99)
```

**Comment by OSkrdgz** [comment]
Issue solved in last commit [1d3aa1f](https://github.com/EDF-Lab/eVDriveFlow/commit/1d3aa1fbc7665f28af152e7a1ac6b000d1fccd9c). GUI was closing before performing stop sequence.

**Comment by OSkrk** [comment]
Hint: After requesting stop charge, session.state is set to 'WaitForPowerDeliveryRequest' which is a common message. However, when the error appears the message to be handled is DC_ChargeLoopRes. https://github.com/EDF-Lab/eVDriveFlow/blob/24d7c777bf195edc2ea648e046236cfe02334e95/evcc/tcp_client.py#L77

**Comment by OSkrk** [comment]
Issue solved with last commit. [f34eb12](https://github.com/EDF-Lab/eVDriveFlow/commit/f34eb1267cdcdd687ecd7c83387fb429aacb459b)
